# configs/model/baseline.yaml
_target_: src.models.wrapper.VesselFM_Refactored
use_fusion: false
spatial_dims: 3
in_channels: 1
out_channels: 1
# 保持与论文一致的 DynUNet 参数
filters: [32, 64, 128, 256, 320, 320]
strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
upsample_kernel_size: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]